# Generated by Django 3.1.4 on 2020-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Варианты', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_description',
            field=models.CharField(max_length=200, verbose_name='Описание опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(max_length=200, verbose_name='Название опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
