# Generated by Django 2.2.10 on 2020-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipolls', '0002_auto_20201202_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст варианта ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(verbose_name='ID Пользователя'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Текст варианта ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=200, verbose_name='Тип вопроса'),
        ),
    ]
